[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "astar"
version = "0.0"

[tool.setuptools]
ext-modules = [
  {name = "astar", sources = ["astar.c"]}
]
